=== AmariahAK/supabase/apps/studio/hooks/custom-content/custom-content.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "type": "object",
  "properties": {
    "$schema": {
      "type": "string"
    },

    "app:title": {
      "type": ["string", "null"],
      "description": "Render a custom HTML title for the site"
    },

    "dashboard_auth:custom_provider": {
      "type": ["string", "null"],
      "description": "Show a custom provider on the sign in page (Continue with X). Will be deprecated by dashboard_auth:custom_providers."
    },

    "dashboard_auth:custom_providers": {
      "type": ["array", "null"],
      "description": "Show a custom provider on the sign in page (Continue with X)",
      "items": {
        "type": "string"
      }
    },

    "docs:row_level_security_guide_path": {
      "type": ["string"],
      "description": "The path to the row level security guide in the docs"
    },

    "organization:legal_documents": {
      "type": ["array", "null"],
      "description": "Renders a provided set of documents under the organization legal documents page",
      "items": {
        "type": "object",
        "properties": {
          "id": { "type": "string" },
          "name": { "type": "string" },
          "description": { "type": "string" },
          "action": {
            "type": "object",
            "properties": {
              "text": { "type": "string" },
              "url": { "type": "string" }
            }
          }
        }
      }
    },

    "project_homepage:client_libraries": {
      "type": "array",
      "description": "Renders a provided set of client libraries under the project's home page",
      "items": {
        "type": "object",
        "properties": {
          "language": { "type": "string" },
          "officialSupport": { "type": "boolean" },
          "releaseState": { "type": "string" },
          "docsUrl": { "type": "string" },
          "gitUrl": { "type": "string" },
          "altIconName": { "type": "string" }
        },
        "required": ["language", "officialSupport", "docsUrl"]
      }
    },
    "project_homepage:example_projects": {
      "type": ["array", "null"],
      "description": "Renders a provided set of example projects under the project's home page",
      "items": {
        "type": "object",
        "properties": {
          "title": { "type": "string" },
          "description": { "type": "string" },
          "iconUrl": { "type": "string" },
          "url": { "type": "string" }
        }
      }
    },

    "logs:default_query": {
      "type": ["string", "null"],
      "description": "Renders a default query when landing on the logs explorer"
    },

    "infra:cloud_providers": {
      "type": ["array"],
      "description": "Filters the valid cloud providers",
      "items": {
        "type": "string",
        "enum": ["AWS", "AWS_K8S", "AWS_NIMBUS", "FLY"]
      }
    },
    "infra:aws_nimbus_label": {
      "type": "string",
      "description": "The label of the AWS Nimbus provider"
    },

    "ssl:certificate_url": {
      "type": "string",
      "description": "The URL of the SSL certificate"
    }
  },
  "required": [
    "app:title",
    "docs:row_level_security_guide_path",
    "organization:legal_documents",
    "project_homepage:client_libraries",
    "project_homepage:example_projects",
    "logs:default_query",
    "infra:cloud_providers",
    "infra:aws_nimbus_label",
    "ssl:certificate_url"
  ],
  "additionalProperties": false
}

=== AmariahAK/supabase/apps/studio/hooks/custom-content/custom-content.json
{
  "$schema": "./custom-content.schema.json",

  "app:title": null,

  "dashboard_auth:custom_provider": null,

  "dashboard_auth:custom_providers": null,

  "docs:row_level_security_guide_path": "/guides/auth/row-level-security",

  "organization:legal_documents": null,

  "project_homepage:client_libraries": [
    {
      "language": "JavaScript",
      "officialSupport": true,
      "docsUrl": "https://supabase.com/docs/reference/javascript/installing",
      "gitUrl": "https://github.com/supabase/supabase-js"
    },
    {
      "language": "Flutter",
      "officialSupport": true,
      "docsUrl": "https://supabase.com/docs/reference/dart/installing",
      "gitUrl": "https://github.com/supabase/supabase-flutter"
    },
    {
      "language": "Python",
      "officialSupport": true,
      "releaseState": "Alpha",
      "docsUrl": "https://supabase.com/docs/reference/python/initializing",
      "gitUrl": "https://github.com/supabase/supabase-py"
    },
    {
      "language": "C#",
      "officialSupport": false,
      "docsUrl": "https://supabase.com/docs/reference/csharp/installing",
      "gitUrl": "https://github.com/supabase-community/supabase-csharp",
      "altIconName": "c-sharp"
    },
    {
      "language": "Swift",
      "officialSupport": true,
      "docsUrl": "https://supabase.com/docs/reference/swift/initializing",
      "gitUrl": "https://github.com/supabase/supabase-swift"
    },
    {
      "language": "Kotlin",
      "officialSupport": false,
      "docsUrl": "https://supabase.com/docs/reference/kotlin/installing",
      "gitUrl": "https://github.com/supabase-community/supabase-kt"
    }
  ],
  "project_homepage:example_projects": null,

  "logs:default_query": null,

  "infra:cloud_providers": ["AWS", "AWS_K8S", "FLY"],
  "infra:aws_nimbus_label": "AWS Nimbus",

  "ssl:certificate_url": "https://supabase-downloads.s3-ap-southeast-1.amazonaws.com/${env}/ssl/${env}-ca-2021.crt"
}
